<section id="head">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h1>
                    Compartilhe prazer
                </h1>
            </div>
            <div class="col-lg-5">
                <div id="transparent">
                    <?php echo $this->form; ?>
                    <p class="small text-center">
                        Ao criar o perfil você aceita nossa 
                        <a href="">Política de Privacidade</a> e
                        <a href="">Termos de uso</a>
                    </p>
                </div>
            </div>
        </div>    
    </div>
</section>


